version: 2

jobs:
    setup_yarn_deps:
      docker:
        - image: circleci/node:7.10
      steps:
        - checkout
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-{{ .Branch }}
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}}-master
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-
        - run: yarn install
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "/tmp/cache_buster" }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
                - node_modules/
    build:
      docker:
        - image: circleci/node:7.10
      steps:
        - checkout
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-{{ .Branch }}
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}}-master
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-
        - run: yarn build
        - save_cache:
            key: dist-{{ .Revision }}
            paths:
              - ./dist
    deploy_to_gcf:
      docker:
        - image: google/cloud-sdk
          environment:
            GOOGLE_PROJECT_ID: messaging-service-180514
            GOOGLE_COMPUTE_ZONE: us-central1-a
      steps:
        - restore_cache:
            keys:
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-{{ .Branch }}
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}}-master
                - yarn-packages-{{ checksum "/tmp/cache_buster" }}-
                - dist-{{ .Revision }}
        - run:
            name: Setup gcloud
            command: |
              openssl aes-256-cbc -K $encrypted_40ef2f4394e3_key -iv $encrypted_40ef2f4394e3_iv -in client-secret.json.enc -out client-secret.json -d
              gcloud auth activate-service-account --key-file client-secret.json
        - deploy:
            command: |
              cd /home/circleci/project/dist
              gcloud beta functions deploy airtable --set-env-vars apiKey=$apiKey, baseId=$baseId --trigger-http --timeout 540s
workflows:
  version: 2
  workflow1:
    jobs:
      - setup_yarn_deps
      - build:
          requires:
            - setup_yarn_deps
      - deploy_to_gcf:
          requires:
            - setup_yarn_deps
            - build
          filters:
            branches:
              only:
                - master